# Course step 2 - Basic Data Exploration

In [2]:
import pandas as pd

# load and review the data
iowa_file_path = "train.csv"
raw_data = pd.read_csv(iowa_file_path)
        
raw_data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

# Course step 3 - Your First Machine Learning Model

In [3]:
columns = raw_data.columns
data = raw_data

y = data.SalePrice
feature_names = ["LotArea", "YearBuilt", "1stFlrSF", "2ndFlrSF", "FullBath", "BedroomAbvGr", "TotRmsAbvGrd"]

X = data[feature_names]
X.dropna(axis=0)
X.describe()
# X.head()

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,10516.828082,1971.267808,1162.626712,346.992466,1.565068,2.866438,6.517808
std,9981.264932,30.202904,386.587738,436.528436,0.550916,0.815778,1.625393
min,1300.000000,1872.000000,334.000000,0.000000,0.000000,0.000000,2.000000
25%,7553.500000,1954.000000,882.000000,0.000000,1.000000,2.000000,5.000000
50%,9478.500000,1973.000000,1087.000000,0.000000,2.000000,3.000000,6.000000
75%,11601.500000,2000.000000,1391.250000,728.000000,2.000000,3.000000,7.000000
max,215245.000000,2010.000000,4692.000000,2065.000000,3.000000,8.000000,14.000000

In [4]:
# Create and fit model
from sklearn.tree import DecisionTreeRegressor

iowa_model = DecisionTreeRegressor(random_state=1)
iowa_model.fit(X, y)

# make predictions
print(iowa_model.predict(X))
print(iowa_model.predict(X.head()) == y.head())

[208500. 181500. 223500. ... 266500. 142125. 147500.]
0    True
1    True
2    True
3    True
4    True
Name: SalePrice, dtype: bool

# Course step 4 - Model Validation

In [5]:
# split data in training and validation data. Use metrics to measure model accuracy
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

X_train, X_val, y_train, y_val = train_test_split(X, y, random_state=1)
y_train_list = list(y_train)

iowa_model.fit(X_train, y_train)

predictions_in_sample = iowa_model.predict(X_train)
print(mean_absolute_error(y_train, predictions_in_sample))
print(predictions_in_sample[:5])
print(y_train_list[:5])
# for the top few values, the model is perfectly fitted
# however we see the mea is not zero even, so there are some predictions that are not perfect:
print([(i, predictions_in_sample[i], y_train_list[i]) for i in range(len(y_train)) if predictions_in_sample[i] != y_train_list[i]])

predictions_out_sample = iowa_model.predict(X_val)
print(predictions_out_sample[:5])
print(list(y_val)[:5])
print(mean_absolute_error(y_val, predictions_out_sample))
# we see mea is unacceptably high

61.85692541856926
[307000. 223500. 145000. 155000. 140000.]
[307000, 223500, 145000, 155000, 140000]
[(147, np.float64(106250.0), 118000), (205, np.float64(142000.0), 140000), (207, np.float64(134000.0), 136500), (336, np.float64(146500.0), 148000), (346, np.float64(133750.0), 140000), (387, np.float64(144433.33333333334), 149300), (414, np.float64(133750.0), 127500), (447, np.float64(132500.0), 130000), (690, np.float64(146500.0), 145000), (706, np.float64(144433.33333333334), 143000), (735, np.float64(142000.0), 144000), (752, np.float64(106250.0), 94500), (786, np.float64(134000.0), 131500), (857, np.float64(144433.33333333334), 141000), (865, np.float64(132500.0), 130000), (1035, np.float64(132500.0), 137500)]
[186500. 184000. 130000.  92000. 164500.]
[231500, 179500, 122000, 84500, 142000]
29652.931506849316

# Course step 5: Underfitting and Overfitting

In [12]:
n = len(X)
d = iowa_model.get_depth()
L = iowa_model.get_n_leaves()
print(n)
print(d)
print(L)
from math import log
print(log(1500))

1460
25
1070
7.313220387090301

In [25]:
# let's try different numbers of leafs (the default is )
for i in [5, 25, 50, 100, 200, 500, 1000]:
    print()
    print("max_leaf_nodes = ", i)
    parametrized_iowa_model = DecisionTreeRegressor(max_leaf_nodes=i, random_state=2)
    parametrized_iowa_model.fit(X_train, y_train)

    predictions_in_sample = parametrized_iowa_model.predict(X_train)
    print("mea in  sample = ", mean_absolute_error(y_train, predictions_in_sample))
    # print(predictions_in_sample[:5])
    # print(y_train_list[:5])

    # for the top few values, the model is perfectly fitted
    # however we see the mea is not zero even, so there are some predictions that are not perfect:
    # print([(i, predictions_in_sample[i], y_train_list[i]) for i in range(len(y_train)) if predictions_in_sample[i] != y_train_list[i]])

    predictions_out_sample = parametrized_iowa_model.predict(X_val)
    print("mea out sample = ", mean_absolute_error(y_val, predictions_out_sample))
    # print(predictions_out_sample[:5])
    # print(list(y_val)[:5])

max_leaf_nodes =  5
mea in  sample =  36097.99956324829
mea out sample =  35044.51299744237

max_leaf_nodes =  25
mea in  sample =  24261.269669580335
mea out sample =  29016.41319191076

max_leaf_nodes =  50
mea in  sample =  19641.12270205718
mea out sample =  27734.60627230166

max_leaf_nodes =  100
mea in  sample =  15262.47186499531
mea out sample =  27467.348221505792

max_leaf_nodes =  200
mea in  sample =  10135.520856898798
mea out sample =  28402.814931086563

max_leaf_nodes =  500
mea in  sample =  3102.1793266702853
mea out sample =  29299.594656485064

max_leaf_nodes =  1000
mea in  sample =  105.68584474885844
mea out sample =  29721.986301369863

# Course Step 6: Random forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor

forest_model = RandomForestRegressor(random_state=1)
forest_model.fit(X_train, y_train)

predictions_out_sample = forest_model.predict(X_val)
mae = mean_absolute_error(y_val, predictions_out_sample)
print(mae)

# I got 21857, which is better then 27467 I got from DecisionTree with optimal number of leafs

21857.15912981083